import { readdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const packageRoot = dirname(
  require.resolve("@phosphor-icons/react/package.json")
);
const files = await readdir(join(packageRoot, "dist/ssr"));
const names = files
  .filter((file) => file.endsWith(".d.ts") && file !== "index.d.ts")
  .map((file) => file.slice(0, -5))
  .sort();
const lines = names.map((name) => {
  const slug = name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
  return `  "${slug}": () => import("@phosphor-icons/react/dist/ssr/${name}").then((module) => ({ default: module.${name}Icon })),`;
});
await writeFile(
  new URL("../src/internal/phosphor-icon-loaders.ts", import.meta.url),
  `// Generated by scripts/generate-icon-loaders.ts. Regenerate after upgrading Phosphor.\n// Explicit imports let bundlers load only the selected icon.\nexport const phosphorIconLoaders = {\n${lines.join("\n")}\n};\n`
);
